### ISSUE TITLE
Failed Fuzzy search returns a strange format

### ISSUE THREAD

**Issue by multimeric** [ChiriVulpes/scryfall-sdk#45]
If I:
```typescript
const Scry = require("scryfall-sdk");
await Scry.Cards.byName("rstdrdtst", true);
```

I get an object like this, which doesn't actually tell me that I've encountered an error or what the error was:
```json
{
  "data": [],
  "not_found": []
}
```

However querying the actual Scryfall API with a similar request (`curl 'https://api.scryfall.com/cards/named?fuzzy=rstdrdtst'`) , I get a much more helpful response:
```json
{
  "object": "error",
  "code": "not_found",
  "status": 404,
  "details": "No cards found matching “rstdrdtst”"
}
```

It would be great if we could get this response instead.

**Comment by ChiriVulpes** [comment]
If you get no results you can query Scry.error() to get the previous error object I believe? Or something like that. Lemme know if that doesn't work
