### ISSUE TITLE
Card Imagery

### ISSUE THREAD

**Issue by CommandCracker8** [ChiriVulpes/scryfall-sdk#50]
Hiya,

How can I get card imagery through this SDK?

**Comment by ChiriVulpes** [comment]
Card data like that is just stored on the object that Scryfall gives. You don't need to do anything in specific with the sdk; just access `card.image_uris`. It gives an object of image URIs based on the size and such which you can then reference or download with your own code.

If you're having trouble finding something in this sdk's documentation, either use your IDE's suggestions to find things on result objects, or look at the api documentation page on the scryfall website, which describes every field that appears on objects like cards.
