### ISSUE TITLE
Search for a set

### ISSUE THREAD

**Issue by CommandCracker8** [ChiriVulpes/scryfall-sdk#51]
Would it be possible to implement some way for searching for a set by it's name? If not, I'm willing to make a PR.

**Comment by ChiriVulpes** [comment]
[Implemented as of v3.1.0](https://github.com/ChiriVulpes/scryfall-sdk/blob/master/DOCUMENTATION.md#setsbyname-name-string-fuzzy-boolean-promiseset-)

Thanks for the suggestion!
