### ISSUE TITLE
svg_uri missing from CardSymbol

### ISSUE THREAD

**Issue by furgin** [ChiriVulpes/scryfall-sdk#55]
The type CardSymbol does not have the field svg_uri which exists on the object returned from scryfall.

CardSymbol defined here: https://github.com/ChiriVulpes/scryfall-sdk/blob/main/src/api/Symbology.ts
Scryfall API defines it here: https://scryfall.com/docs/api/card-symbols

**Comment by ChiriVulpes** [comment]
Thanks for the report! It's going to be a week or so at minimum before I'm able to fix this one, in the middle of a move atm

**Comment by furgin** [comment]
Thanks @ChiriVulpes ! I have added a PR that hopefully fixes this and the other two issues I raised.
