### ISSUE TITLE
Tagger api support

### ISSUE THREAD

**Issue by ejkkan** [ChiriVulpes/scryfall-sdk#63]
First of all, amazing work on this lib! Thank you for the hard work.

Are there any plans on adding support for the tagger api?
https://tagger.scryfall.com/

**Comment by ChiriVulpes** [comment]
What exactly would support for tagger entail? The `Cards.search` function is just Scryfall's full-text search exactly, so it supports everything described here afaik: https://scryfall.com/docs/tagger-tags

**Comment by ejkkan** [comment]
You are absolutely right, my bad on not doing my due diligence before reaching out...
