### ISSUE TITLE
Scry.Cards.collection method unable to handle split card names

### ISSUE THREAD

**Issue by Joshua-Farr** [ChiriVulpes/scryfall-sdk#71]
Running into issues with sending arrays of split card names using the Cards.collection (...collection: CardIdentifier[]): MagicEmitter<Card> method.

Example code:

```js
export const getAllCardImages = async (cardList: string[]) => {
  const collection = cardList.map((card) => {
    return Scry.CardIdentifier.byName(card);
  });
  const cardUrls = await Scry.Cards.collection(...collection).waitForAll();
  return cardUrls;
};

```

Logging response:

<img width="1195" alt="CleanShot 2024-05-22 at 22 08 20@2x" src="https://github.com/ChiriVulpes/scryfall-sdk/assets/94776350/a10521c8-24c0-4acb-b296-43a5ae6f67c2">

**Comment by ChiriVulpes** [comment]
It seems like this endpoint is bugged on Scryfall's end, it doesn't currently work for multi-face cards like this. (Tested with `Struggle // Survive` (the actual name), `Struggle//Survive`, `Struggle / Survive`, `Struggle/Survive`, and even tried the same with URI encoding just in case. However, it's a little cursed, but technically it does work if you only search for one face of the card. There may be collisions from doing that, though
