### ISSUE TITLE
"C" is present in `Card.produced_mana`

### ISSUE THREAD

**Issue by nyoro-wrl** [ChiriVulpes/scryfall-sdk#73]
The type of `Card.produced_mana` is currently `("W" | "B" | "R" | "U" | "G")[]`, but there are cards that include `"C"` in this array. I propose updating the type to `("W" | "B" | "R" | "U" | "G" | "C")[]`.

Example: Caves of Koilos (DMU) 244

**Comment by ChiriVulpes** [comment]
Oh interesting, that isn't documented. I'll add it, thank you

**Comment by ChiriVulpes** [comment]
Published v5.0.1 with this!

**Comment by nyoro-wrl** [comment]
Thanks!
